name: Release Please

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Release Please Action
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: php
          package-name: jsonifywp
          token: ${{ secrets.GITHUB_TOKEN }}
